# Generated by Django 5.1.6 on 2025-02-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='-', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Address',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Nationality',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
