# Generated by Django 5.1.6 on 2025-02-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_rename_customer_order_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
