# Generated by Django 5.1.6 on 2025-02-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_remove_order_price_order_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='select_service',
            field=models.CharField(blank=True, default='office_shifting', max_length=255, null=True),
        ),
    ]
